# Generated by Django 5.2.5 on 2025-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=11)),
                ('section', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=9)),
                ('course_id', models.CharField(max_length=100)),
                ('enrollment_date', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('schedule_id', models.CharField(max_length=100)),
                ('instructor_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('LRN', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('guardian_contact_no', models.CharField(max_length=11)),
                ('guardian_address', models.CharField(max_length=100)),
                ('last_school_attended', models.CharField(max_length=100)),
            ],
        ),
    ]
